### PR TITLE
Reformatting format_and_worms.py

### PR DESCRIPTION
**Pull request by robertgodfrey**
- Extracted constants and functions from format_and_worms.py and put them in their own files. 
- Added more comments and updated formatting to improve readability
- Remove `KeyError` try-except blocks and replace with if-else statements

### CODE REVIEW

**Comment by robertgodfrey** [comment]
This looks big but there's really not that much to it, mostly just moving the constants and functions to their own separate files. I can go over this on Thursday with someone if anyone's interested.

**Comment by boahelenshin** [comment]
initially few thoughts: 
- there are few more opportunities to decouple the formatting and WORMS (1. format.py 2. worms.py)
- custom exceptions are good! but what happened to DiveNotFoundException?
- break some of the larger nested loops into smaller functions

**Comment by robertgodfrey** [comment]
Working on taking out WoRMS to its own file now. 

The DiveNotException class was defined as 
```
class DiveNotFoundException(Exception):
    pass
```

The only reference to the exception was here:
```
def get_dive_row(dive_name):
    for row in dive_info:
        if row[0] in dive_name or dive_name in row[0]:
            return row
    raise DiveNotFoundException('Dive is not in provided CSV file')
```
which raised the exception if the dive was not listed in the Dives.csv file

The exception was then caught here:
```
try:
    dive_row = get_dive_row(dive_name)
except DiveNotFoundException:
    print('Dive {0} not found in Dives.csv file. Make sure a row has been added with the required data fields.')
```
which means the exception was pointless, right? If it's caught, it doesn't actually do anything. That's my understanding, please lmk if I'm wrong.

**Comment by robertgodfrey** [comment]
My replacement: 
```
dive_row = next((row for row in dive_info if row[0] in dive_name or dive_name in row[0]), None)
if not dive_row:
    print('\n###################################################################')
    print(f'ERROR: Dive "{dive_name}" not found in Dives.csv file.')
    print('This dive must be added to Dives.csv to continue processing.')
    print('###################################################################\n')
    break
```
Initializes `dive_row` as the row of data in the excel file if the dive name matches, or None if it doesn't match. 
If `dive_row` is None, an error prints and the program stops.

**Pull request merged**
